import json, requests, random

API = "http://127.0.0.1:8188/prompt"

def node(class_type, **inputs):
    return {"class_type": class_type, "inputs": inputs}

prompt = {
    "75": node("UNETLoader",
        unet_name="wan2.2_t2v_high_noise_14B_fp8_scaled.safetensors",
        weight_dtype="default"),
    "76": node("UNETLoader",
        unet_name="wan2.2_t2v_low_noise_14B_fp8_scaled.safetensors",
        weight_dtype="default"),
    "71": node("CLIPLoader",
        clip_name="umt5_xxl_fp8_e4m3fn_scaled.safetensors",
        type="wan"),
    "73": node("VAELoader",
        vae_name="wan_2.1_vae.safetensors"),
    "89": node("CLIPTextEncode",
        clip=("71", 0),
        text="Cinematic aerial shot of a misty mountain landscape at sunrise, golden light piercing through clouds"),
    "72": node("CLIPTextEncode",
        clip=("71", 0),
        text="blurry, low quality, distorted"),
    "74": node("EmptyHunyuanLatentVideo",
        width=512,
        height=512,
        length=81,
        batch_size=1),
    "82": node("ModelSamplingSD3",
        model=("75", 0),
        shift=5.0),
    "86": node("ModelSamplingSD3",
        model=("76", 0),
        shift=5.0),
    "81": node("KSamplerAdvanced",
        model=("82", 0),
        positive=("89", 0),
        negative=("72", 0),
        latent_image=("74", 0),
        add_noise="enable",
        noise_seed=random.randint(0, 2**63),
        steps=4,
        cfg=1.0,
        sampler_name="euler",
        scheduler="simple",
        start_at_step=0,
        end_at_step=2,
        return_with_leftover_noise="enable"),
    "78": node("KSamplerAdvanced",
        model=("86", 0),
        positive=("89", 0),
        negative=("72", 0),
        latent_image=("81", 0),
        add_noise="disable",
        noise_seed=0,
        steps=4,
        cfg=1.0,
        sampler_name="euler",
        scheduler="simple",
        start_at_step=2,
        end_at_step=4,
        return_with_leftover_noise="disable"),
    "87": node("VAEDecode",
        samples=("78", 0),
        vae=("73", 0)),
    "88": node("CreateVideo",
        images=("87", 0),
        fps=16),
    "80": node("SaveVideo",
        video=("88", 0),
        filename_prefix="wan22_exact",
        format="auto",
        codec="auto"),
}

r = requests.post(API, json={"prompt": prompt})
print(r.status_code, r.text[:500])
